import { ArrowUpRight, ChevronRight, Trophy } from "lucide-react";
import type { GameResult, SeasonState, ScheduledGame, Team, UserCoach } from "../../domain/types";
import { defaultLineup } from "../../data/teams";
import { getStandings } from "../../season/season";
import { CoachAvatar, PlayerAvatar } from "../components/Avatar";
import { TeamMark } from "../components/TeamMark";
import type { MainView } from "../components/BottomNav";

export function ProgramHome({ team, opponent, result, season, nextGame, gameInProgress = false, coach, onNavigate, onPregame }: { team: Team; opponent: Team; result: GameResult | null; season: SeasonState; nextGame?: ScheduledGame; gameInProgress?: boolean; coach?: UserCoach; onNavigate: (view: MainView) => void; onPregame: () => void }) {
  const won = result?.winnerId === team.id;
  const record = season.records[team.id];
  const conferenceStanding = getStandings(season, team.conference).findIndex((entry) => entry.teamId === team.id) + 1;
  const recentResults = season.schedule.filter((game) => game.status === "completed" && game.result && (game.homeTeamId === team.id || game.awayTeamId === team.id)).slice(-3).reverse();
  const starters = defaultLineup(team).map((id) => team.roster.find((player) => player.id === id)).filter((player): player is Team["roster"][number] => Boolean(player));
  const threePoint = Math.round(starters.reduce((sum, player) => sum + player.ratings.threePoint, 0) / starters.length);
  const defense = Math.round(starters.reduce((sum, player) => sum + (player.ratings.perimeterDefense + player.ratings.interiorDefense) / 2, 0) / starters.length);
  return <div className="screen-stack">
    <section className="program-hero" style={{ borderLeftColor: team.colors[0] }}>
      <div className="program-hero-top"><span className="eyebrow light">YOUR PROGRAM · {season.seasonYear}</span><span className="program-hero-mark">{team.logo}</span></div>
      <div className="program-hero-copy"><TeamMark team={team} size="lg" /><div><h1>{team.name}</h1><p>{team.nickname} · {team.city}</p></div></div>
      <div className="program-hero-bottom"><div><span>RECORD</span><b>{record.wins}–{record.losses}</b></div><div><span>CONFERENCE</span><b>{record.conferenceWins}–{record.conferenceLosses}</b></div><div><span>CONF. PLACE</span><b>#{conferenceStanding}</b></div><div><span>HEAD COACH</span><b>{coach ? `${coach.firstName} ${coach.lastName}` : team.coach.name}</b></div></div>
    </section>
    <section className="section-block"><div className="section-label"><span>{gameInProgress ? "GAME IN PROGRESS" : nextGame ? "UP NEXT" : "SEASON STATUS"}</span>{nextGame && <button onClick={onPregame}>{gameInProgress ? "Resume game" : "Pregame hub"} <ArrowUpRight size={14} /></button>}</div>
      {nextGame ? <><button className="matchup-card" onClick={onPregame}><div><span className="eyebrow">{gameInProgress ? "LIVE · COACHING WINDOW" : `DAY ${nextGame.day} · ${nextGame.homeTeamId === team.id ? "HOME" : "AWAY"}`}</span><h2>{opponent.name}</h2><p>{opponent.nickname} · {season.records[opponent.id].wins}–{season.records[opponent.id].losses}</p></div><div className="matchup-logos"><TeamMark team={team} size="md" /><span>{nextGame.homeTeamId === team.id ? "VS" : "AT"}</span><TeamMark team={opponent} size="md" /><ChevronRight size={18} /></div></button><button className="primary-action home-primary" onClick={onPregame}>{gameInProgress ? "Resume Game" : "Prepare for Game"}<span>→</span></button></> : <div className="matchup-card"><div><span className="eyebrow">SEASON COMPLETE</span><h2>{record.wins}–{record.losses}</h2><p>Finished #{conferenceStanding} in the {team.conference} Conference</p></div><Trophy size={22} /></div>}
    </section>
    {result && <section className="section-block"><div className="section-label"><span>RECENT RESULTS</span><button onClick={() => onNavigate("season")}>Full schedule <ArrowUpRight size={14} /></button></div>{recentResults.length ? recentResults.map((game) => { const gameResult = game.result!; const gameWon = gameResult.winnerId === team.id; const gameOpponent = season.teams.find((candidate) => candidate.id === (game.homeTeamId === team.id ? game.awayTeamId : game.homeTeamId))!; return <div className={`result-strip ${gameWon ? "win" : "loss"}`} key={game.id}><div><span className="eyebrow">DAY {game.day} · FINAL</span><strong>{gameWon ? "WIN" : "LOSS"}</strong><p>{game.homeTeamId === team.id ? "vs" : "at"} {gameOpponent.name}</p></div><b>{gameResult.home.stats.points} <i>—</i> {gameResult.away.stats.points}</b><Trophy size={19} /></div>; }) : <div className={`result-strip ${won ? "win" : "loss"}`}><div><span className="eyebrow">FINAL</span><strong>{won ? "WIN" : "LOSS"}</strong><p>{result.away.team.id === team.id ? "at" : "vs"} {result.away.team.id === team.id ? result.home.team.name : result.away.team.name}</p></div><b>{result.home.stats.points} <i>—</i> {result.away.stats.points}</b><Trophy size={19} /></div>}</section>}
    <section className="home-columns"><div><div className="section-label"><span>STARTING FIVE</span><button onClick={() => onNavigate("lineup")}>Rotation <ArrowUpRight size={14} /></button></div><div className="home-starters">{starters.map((player) => <div key={player.id}><PlayerAvatar player={player} team={team} size={30} /><span><b>{player.name}</b><small>{player.position} · {player.classYear}</small></span><strong>{player.ratings.overall}</strong></div>)}</div></div><div><div className="section-label"><span>SCOUTING NOTES</span></div><div className="insight-list"><p><b>Strength</b><span>{threePoint >= 78 ? "Spacing and perimeter shooting" : "Interior scoring and size"}</span></p><p><b>Watch</b><span>{defense >= 78 ? "Protect the glass" : "Point-of-attack defense"}</span></p></div></div></section>
    <section className="section-block"><div className="section-label"><span>STAFF NOTES</span></div><div className="staff-note">{coach ? <CoachAvatar coach={coach} team={team} size={32} /> : <div className="coach-initials">{team.coach.name.split(" ").map((part) => part[0]).join("")}</div>}<div><p>“Our identity starts with the five on the floor. Build a lineup that can defend and share the ball.”</p><span>{coach ? `${coach.firstName} ${coach.lastName} · ${coach.archetype}` : `${team.coach.name} · ${team.coach.style}`}</span></div></div></section>
    <section className="quick-links"><button onClick={() => onNavigate("roster")}><span><span className="quick-icon">01</span><b>Manage roster</b></span><ChevronRight size={17} /></button><button onClick={() => onNavigate("lineup")}><span><span className="quick-icon">02</span><b>Set rotation</b></span><ChevronRight size={17} /></button><button onClick={() => onNavigate("gameplan")}><span><span className="quick-icon">03</span><b>Build game plan</b></span><ChevronRight size={17} /></button></section>
  </div>;
}
