import { CalendarClock, ChevronRight, FastForward, Trophy } from "lucide-react";
import { useState } from "react";
import type { ScheduledGame, SeasonState, Team } from "../../domain/types";
import { getNextUserGame, getStandings } from "../../season/season";
import { PlayerAvatar } from "../components/Avatar";
import { ScreenHeader } from "../components/ScreenHeader";
import { TeamMark } from "../components/TeamMark";

function gameLabel(game: ScheduledGame, team: Team, teams: Team[]): string {
  const opponentId = game.homeTeamId === team.id ? game.awayTeamId : game.homeTeamId;
  const opponent = teams.find((candidate) => candidate.id === opponentId);
  return `${game.homeTeamId === team.id ? "vs" : "at"} ${opponent?.shortName ?? "Opponent"}`;
}

export function SeasonScreen({ state, team, onAdvanceDay, onAdvanceNextGame, onPlayNextGame }: { state: SeasonState; team: Team; onAdvanceDay: () => void; onAdvanceNextGame: () => void; onPlayNextGame: () => void }) {
  const [tab, setTab] = useState<"schedule" | "standings" | "stats">("schedule");
  const record = state.records[team.id];
  const nextGame = getNextUserGame(state);
  const standings = getStandings(state, team.conference);
  const rank = standings.findIndex((entry) => entry.teamId === team.id) + 1;
  const visibleGames = state.schedule.filter((game) => game.homeTeamId === team.id || game.awayTeamId === team.id).filter((game) => game.status === "completed" || game.day >= state.currentDay).slice(0, 8);
  const leaders = Object.values(state.playerStats).filter((player) => player.gamesPlayed > 0).sort((a, b) => b.points - a.points).slice(0, 3).map((stats) => ({ stats, player: state.teams.flatMap((candidate) => candidate.roster).find((player) => player.id === stats.playerId), team: state.teams.find((candidate) => candidate.roster.some((player) => player.id === stats.playerId)) }));
  return <div className="screen-stack season-screen"><ScreenHeader eyebrow={`${state.seasonYear}–${String(state.seasonYear + 1).slice(-2)} · ${team.conference} CONFERENCE`} title="Season" subtitle={`Day ${state.currentDay} of ${state.totalDays} · ${state.history.length} games complete`} />
    <section className="season-summary"><div><span>RECORD</span><strong>{record.wins}–{record.losses}</strong></div><div><span>CONF.</span><strong>{record.conferenceWins}–{record.conferenceLosses}</strong></div><div><span>STANDING</span><strong>{rank ? `${rank}${rank === 1 ? "st" : rank === 2 ? "nd" : rank === 3 ? "rd" : "th"}` : "—"}</strong></div><div><span>POINT DIFF</span><strong>{record.pointsFor - record.pointsAgainst >= 0 ? "+" : ""}{record.pointsFor - record.pointsAgainst}</strong></div></section>
    {nextGame ? <section className="next-game"><div className="section-label"><span>NEXT GAME · DAY {nextGame.day}</span><span>{nextGame.conferenceGame ? "Conference" : "Non-conference"}</span></div><div className="next-game-main"><div><span className="eyebrow">{nextGame.homeTeamId === team.id ? "HOME" : "AWAY"}</span><h2>{gameLabel(nextGame, team, state.teams)}</h2><p>{state.teams.find((candidate) => candidate.id === (nextGame.homeTeamId === team.id ? nextGame.awayTeamId : nextGame.homeTeamId))?.name}</p></div><TeamMark team={state.teams.find((candidate) => candidate.id === (nextGame.homeTeamId === team.id ? nextGame.awayTeamId : nextGame.homeTeamId)) ?? team} size="md" /></div><div className="season-actions"><button className="primary-action" onClick={onPlayNextGame}>Play next game <span>→</span></button><button className="quiet-action" onClick={onAdvanceNextGame}><FastForward size={14} /> Advance to game</button><button className="quiet-action" onClick={onAdvanceDay}><CalendarClock size={14} /> Simulate day</button></div></section> : <section className="season-finished"><Trophy size={20} /><div><b>Season complete</b><span>Review your final record and conference finish.</span></div></section>}
    <nav className="season-tabs" aria-label="Season views"><button className={tab === "schedule" ? "active" : ""} onClick={() => setTab("schedule")}>Schedule</button><button className={tab === "standings" ? "active" : ""} onClick={() => setTab("standings")}>Standings</button><button className={tab === "stats" ? "active" : ""} onClick={() => setTab("stats")}>Stats</button></nav>
    {tab === "schedule" && <section><div className="section-label"><span>TEAM SCHEDULE</span><span>{state.schedule.filter((game) => game.homeTeamId === team.id || game.awayTeamId === team.id).length} games</span></div><div className="schedule-list">{visibleGames.map((game) => { const completed = game.status === "completed"; const result = game.result; const won = completed && result ? result.winnerId === team.id : false; const opponentId = game.homeTeamId === team.id ? game.awayTeamId : game.homeTeamId; const opponent = state.teams.find((candidate) => candidate.id === opponentId) ?? team; return <div className={`schedule-row ${completed ? "completed" : "upcoming"}`} key={game.id}><span className="schedule-day">D{game.day}</span><TeamMark team={opponent} size="sm" /><div><b>{game.homeTeamId === team.id ? "vs" : "at"} {opponent.shortName}</b><small>{game.conferenceGame ? "Conference" : "Non-conference"}</small></div>{completed ? <strong className={won ? "result-win" : "result-loss"}>{won ? "W" : "L"} {result?.home.stats.points}–{result?.away.stats.points}</strong> : <span className="scheduled-chip">UPCOMING</span>}<ChevronRight size={14} /></div>; })}</div></section>}
    {tab === "standings" && <section><div className="section-label"><span>{team.conference.toUpperCase()} STANDINGS</span><span><CalendarClock size={13} /> {state.history.length}/{state.schedule.length}</span></div><div className="standings-list standings-head"><div><span>#</span><span>TEAM</span><span>CONF</span><span>OVERALL</span></div>{standings.map((entry, index) => { const standingTeam = state.teams.find((candidate) => candidate.id === entry.teamId)!; return <div className={`standing-row ${entry.teamId === team.id ? "user-standing" : ""}`} key={entry.teamId}><span>{index + 1}</span><TeamMark team={standingTeam} size="sm" /><b>{standingTeam.shortName}</b><span>{entry.conferenceWins}–{entry.conferenceLosses}</span><strong>{entry.wins}–{entry.losses}</strong></div>; })}</div></section>}
    {tab === "stats" && leaders.length > 0 && <section><div className="section-label"><span>SEASON LEADERS</span><span>POINTS</span></div><div className="season-leaders">{leaders.map(({ stats, player, team: playerTeam }) => player && playerTeam ? <div key={player.id}><PlayerAvatar player={player} team={playerTeam} size={38} /><span><b>{player.name}</b><small>{playerTeam.shortName} · {stats.gamesPlayed} GP</small></span><strong>{(stats.points / Math.max(1, stats.gamesPlayed)).toFixed(1)}<small>PPG</small></strong></div> : null)}</div></section>}
  </div>;
}
